default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: rails
  password: rails
  port: 5432

development:
  <<: *default
  database: scrabble_club_development

test:
  <<: *default
  host: 127.0.0.1
  database: scrabble_club_test

production:
  <<: *default
  database: scrabble_club_production
  username: scrabble_club
  password: <%= ENV['SCRABBLE_CLUB_DATABASE_PASSWORD'] %>
